appointments/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^appointments', include('reminders.urls')),

    # Include the Django admin
    url(r'^admin/', include(admin.site.urls)),
]

reminders/urls.py
from django.conf.urls import url

from .views import AppointmentListView, AppointmentCreateView, AppointmentDetailView, AppointmentUpdateView, AppointmentDeleteView


urlpatterns = [
    # List and detail views
    url(r'^$', AppointmentListView.as_view(), name='list_appointments'),
    url(r'^/(?P<pk>[0-9]+)$', AppointmentDetailView.as_view(), name='view_appointment'),

    # Create, update, delete
    url(r'^/new$', AppointmentCreateView.as_view(), name='new_appointment'),
    url(r'^/(?P<pk>[0-9]+)/edit$', AppointmentUpdateView.as_view(), name='edit_appointment'),
    url(r'^/(?P<pk>[0-9]+)/delete$', AppointmentDeleteView.as_view(), name='delete_appointment'),
]

reminders/models.py
from __future__ import unicode_literals

from appointments.settings import celery_app
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from timezone_field import TimeZoneField

import arrow


@python_2_unicode_compatible
class Appointment(models.Model):
    name = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=15)
    time = models.DateTimeField()
    time_zone = TimeZoneField(default='US/Pacific')

    # Additional fields not visible to users
    task_id = models.CharField(max_length=50, blank=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Appointment #{0} - {1}'.format(self.pk, self.name)

    def get_absolute_url(self):
        return reverse('view_appointment', args=[str(self.id)])

    def clean(self):
        """Checks that appointments are not scheduled in the past"""

        appointment_time = arrow.get(self.time, self.time_zone.zone)

        if appointment_time < arrow.utcnow():
            raise ValidationError('You cannot schedule an appointment for the past. Please check your time and time_zone')

    def schedule_reminder(self):
        """Schedules a Celery task to send a reminder about this appointment"""

        # Calculate the correct time to send this reminder
        appointment_time = arrow.get(self.time, self.time_zone.zone)
        reminder_time = appointment_time.replace(minutes=-settings.REMINDER_TIME)

        # Schedule the Celery task
        from .tasks import send_sms_reminder
        result = send_sms_reminder.apply_async((self.pk,), eta=reminder_time)

        return result.id

    def save(self, *args, **kwargs):
        """Custom save method which also schedules a reminder"""

        # Check if we have scheduled a reminder for this appointment before
        if self.task_id:
            # Revoke that task in case its time has changed
            celery_app.control.revoke(self.task_id)

        # Save our appointment, which populates self.pk,
        # which is used in schedule_reminder
        super(Appointment, self).save(*args, **kwargs)

        # Schedule a new reminder task for this appointment
        self.task_id = self.schedule_reminder()

        # Save our appointment again, with the new task_id
        super(Appointment, self).save(*args, **kwargs)

reminders/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .models import Appointment

class AppointmentListView(ListView):
    """Shows users a list of appointments"""

    model = Appointment


class AppointmentDetailView(DetailView):
    """Shows users a single appointment"""

    model = Appointment


class AppointmentCreateView(SuccessMessageMixin, CreateView):
    """Powers a form to create a new appointment"""

    model = Appointment
    fields = ['name', 'phone_number', 'time', 'time_zone']
    success_message = 'Appointment successfully created.'


class AppointmentUpdateView(SuccessMessageMixin, UpdateView):
    """Powers a form to edit existing appointments"""

    model = Appointment
    fields = ['name', 'phone_number', 'time', 'time_zone']
    success_message = 'Appointment successfully updated.'


class AppointmentDeleteView(DeleteView):
    """Prompts users to confirm deletion of an appointment"""

    model = Appointment
    success_url = reverse_lazy('list_appointments')

templates/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %} - Twilio Appointment Reminders</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- CSS -->
    {% bootstrap_css %}

    {% block page_css %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Appointment Reminders</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'new_appointment' %}">New</a></li>
            <li><a href="{% url 'list_appointments' %}">List</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}

      {% block content %}{% endblock content %}

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

    <!-- JavaScript -->
    {% bootstrap_javascript jquery=1 %}

    {% block page_js %}{% endblock %}

  </body>

</html>
 

templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-lg-9">
      
      <h1>Appointment Reminders with Django</h1>

      <p>This demo application will show you how to implement SMS appointment reminders with <a href="http://twilio.com">Twilio</a> in Django.

      <p><a class="btn btn-primary btn-xs" href="{% url 'new_appointment' %}">Create a new Appointment</a> to see how it works!</p>

    </div>

  </div><!--/row-->
{% endblock %}

templates/reminders/appointment_confirm_delete.html
{% extends "base.html" %}

{% block title %}{{ appointment }}{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-lg-9">
      <div class="page-header">
        <h1>Confirm deletion</h1>
      </div>

      <form action="" method="post">
          {% csrf_token %}
          <p>Are you sure you want to delete <strong>{{ object }}</strong>?</p>
          <a class="btn btn-default" href="javascript:history.back()">Back</a>
          <button type="submit" class="btn btn-danger">Delete</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/reminders/appointment_detail.html
{% extends "base.html" %}

{% block title %}{{ appointment }}{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-lg-9">
      <div class="page-header">
        <h1>Appointment</h1>
      </div>

      <dl class="dl-horizontal">
        <dt><strong>Name:</strong></dt>
        <dd>{{ appointment.name }}</dd>
        <dt><strong>Phone number:</strong></dt>
        <dd>{{ appointment.phone_number }}</dd>
        <dt><strong>Time:</strong></dt>
        <dd>{{ appointment.time }}</dd>
        <dt><strong>Time zone:</strong></dt>
        <dd>{{ appointment.time_zone }}</dd>
      </dl>

      <a class="btn btn-default" href="{% url 'list_appointments' %}">Back</a>
      <a class="btn btn-default" href="{% url 'edit_appointment' appointment.id %}">Edit</a>
      <a class="btn btn-danger" data-method="delete" href="{% url 'delete_appointment' appointment.id %}">Delete</a>
    </div>
  </div>
{% endblock %}

templates/reminders/appointment_form.html
{% extends "base.html" %}

{% load bootstrap_tags %}

{% block title %}New reminder{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-lg-9">
      <div class="page-header">
        <h1>
          {% if not object.pk %}
            New appointment
          {% else %}
            Edit appointment
          {% endif %}
          </h1>
      </div>

      <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form|as_bootstrap_horizontal }}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <a href="#back" class="btn btn-default">Cancel</a>
            <button type="submit" class="btn btn-primary">
              {% if not object.pk %}
                Create appointment
              {% else %}
                Update appointment
              {% endif %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

{% block page_css %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block page_js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

  <script type="text/javascript">
      $(function() {
          $('#id_time').datetimepicker({
            format: 'MM/DD/YYYY HH:mm',
            extraFormats: ['YYYY-MM-DD HH:mm:ss'],
            sideBySide: true
          });
      });
  </script>
{% endblock %}

templates/reminders/appointment_list.html
{% extends "base.html" %}

{% block title %}Upcoming reminders{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-lg-9">

      <div class="page-header">
        <h1>Appointments</h1>
      </div>

      {% if not object_list %}
        <p><strong>No upcoming appointments.</strong> Why not <a href="{% url 'new_appointment' %}">schedule one?</a>
      {% endif %}

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Phone number</th>
            <th>Time</th>
            <th>Created at</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for appointment in object_list %}
            <tr>
              <td><a href="{{ appointment.get_absolute_url }}">{{ appointment.pk }}</a></td>
              <td>{{ appointment.name }}</td>
              <td>{{ appointment.phone_number }}</td>
              <td>{{ appointment.time }}</td>
              <td>{{ appointment.created }}</td>
              <td>
                <a class="btn btn-default btn-xs" href="{% url 'edit_appointment' appointment.pk %}">Edit</a>
                <a class="btn btn-xs btn-danger" href="{% url 'delete_appointment' appointment.pk %}">Delete</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <a class="btn btn-primary" href="{% url 'new_appointment' %}">New</a>
    </div>
  </div>
{% endblock %}